#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ugfx_example
#If UGFX_COMPONENT_PATH is not defined, use relative path as default value
UGFX_COMPONENT_PATH ?= $(abspath $(shell pwd)/../)
 
include $(UGFX_COMPONENT_PATH)/components/component_conf.mk
include $(IDF_PATH)/make/project.mk